apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: devops-mahir-submission-2-ns
  labels:
    app: karsajobs
    tier: frontend
spec:
  ports:
    - port: 8000
      targetPort: 8000
      protocol: TCP
      # nodePort: 30081
  selector:
    tier: frontend
  type: NodePort
