apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongo
  namespace: devops-mahir-submission-2-ns
  labels:
    app: mongo
spec:
  selector:
    matchLabels:
      app: mongo
      tier: data
  serviceName: mongo
  minReadySeconds: 10
  template:
    metadata:
      labels:
        app: mongo
        tier: data
    spec:
      terminationGracePeriodSeconds: 10
      containers:
        - image: mongo:latest
          name: mongo
          env:
            - name: MONGO_INITDB_ROOT_USERNAME_FILE
              value: /etc/mongo-credentials/MONGO_ROOT_USERNAME
            - name: MONGO_INITDB_ROOT_PASSWORD_FILE
              value: /etc/mongo-credentials/MONGO_ROOT_PASSWORD
          ports:
            - containerPort: 27017
              name: mongo
          volumeMounts:
            - name: mongo-persistent-volume
              mountPath: /data/db
            - name: mongo-configmap
              mountPath: /config
            - name: mongo-credential
              mountPath: /etc/mongo-credentials
      volumes:
        - name: mongo-persistent-volume
          persistentVolumeClaim:
            claimName: mongo-pv-claim
        - name: mongo-configmap
          configMap:
            name: mongo-config
        - name: mongo-credential
          secret:
            secretName: mongo-credential
