apiVersion: v1
# jenis object service
kind: Service
# berinama service yaitu order dan
# masukkan ke namespace devops-mahir-submission-3-ns
metadata:
  name: order
  namespace: devops-mahir-submission-3-ns
  labels:
    app: order-shipping
    tier: order
spec:
  # buka port 3000 dan reroute ke port 3000
  # pod yang dialokasikan yaitu yang memiliki label order
  ports:
    - port: 3000
      targetPort: 3000
      name: tcp
      protocol: TCP
  selector:
    tier: order
  # tipe service yaitu nodeport agar bisa diakses dari eksternal cluster
  type: NodePort
