apiVersion: v1
# jenis object service
kind: Service
# berinama service yaitu shippping dan
# masukkan ke namespace devops-mahir-submission-3-ns
metadata:
  name: shipping
  namespace: devops-mahir-submission-3-ns
  labels:
    app: order-shipping
    tier: shipping
spec:
  ports:
    # buka port 3001 dan reroute ke port pod 3001
    # pod yang dialokasikan yaitu yang memiliki label shipping
    - port: 3001
      targetPort: 3001
      name: tcp
      protocol: TCP
  selector:
    tier: shipping
  # tipe service yaitu nodeport
  # tipe service yaitu nodeport agar bisa diakses dari eksternal cluster
  type: NodePort
