apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: devops-mahir-submission-2-ns
  labels:
    app: karsajobs
    tier: backend
spec:
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
      # name: http
  selector:
    tier: backend
  type: ClusterIP
